from PyQt5 import QtCore, QtGui, QtWidgets

from TestAutomation.admin.InitUserDevice.InitUserDeviceController import InitUserDeviceController

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 747)
        MainWindow.setStyleSheet("background-color: rgb(108, 108, 108);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Reset = QtWidgets.QLabel(self.centralwidget)
        self.Reset.setGeometry(QtCore.QRect(30, 100, 111, 16))
        self.Reset.setObjectName("Reset")
        self.stateBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.stateBrowser.setGeometry(QtCore.QRect(510, 150, 261, 501))
        self.stateBrowser.setAutoFillBackground(False)
        self.stateBrowser.setStyleSheet("background-color: rgb(190, 190, 190)")
        self.stateBrowser.setObjectName("stateBrowser")
        self.State = QtWidgets.QLabel(self.centralwidget)
        self.State.setGeometry(QtCore.QRect(510, 130, 56, 12))
        self.State.setStyleSheet("color: rgb(255, 255, 255);")
        self.State.setObjectName("State")
        self.ResetInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.ResetInfo.setGeometry(QtCore.QRect(30, 250, 451, 61))
        self.ResetInfo.setStyleSheet("color: rgb(255, 255, 255);")
        self.ResetInfo.setFlat(False)
        self.ResetInfo.setCheckable(False)
        self.ResetInfo.setObjectName("ResetInfo")
        self.label_5 = QtWidgets.QLabel(self.ResetInfo)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 56, 12))
        self.label_5.setObjectName("label_5")
        self.TestID = QtWidgets.QLineEdit(self.ResetInfo)
        self.TestID.setText("Enter the ResetID")
        self.TestID.setEnabled(True)
        self.TestID.setGeometry(QtCore.QRect(49, 25, 113, 20))
        self.TestID.setMouseTracking(True)
        self.TestID.setFrame(False)
        self.TestID.setObjectName("TestID")
        self.SERIES = QtWidgets.QLabel(self.centralwidget)
        self.SERIES.setGeometry(QtCore.QRect(30, 20, 331, 49))
        self.SERIES.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.SERIES.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.SERIES.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.SERIES.setObjectName("SERIES")
        self.StartBtn = QtWidgets.QPushButton(self.centralwidget)
        self.StartBtn.setGeometry(QtCore.QRect(150, 530, 75, 23))
        self.StartBtn.setStyleSheet("background-color: rgb(206, 206, 206);\n"
"")
        self.StartBtn.setObjectName("StartBtn")
        self.ResetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ResetBtn.setGeometry(QtCore.QRect(250, 530, 75, 23))
        self.ResetBtn.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.ResetBtn.setObjectName("ResetBtn")
        self.UserInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.UserInfo.setGeometry(QtCore.QRect(30, 150, 451, 61))
        self.UserInfo.setStyleSheet("color: rgb(255, 255, 255);")
        self.UserInfo.setFlat(False)
        self.UserInfo.setCheckable(False)
        self.UserInfo.setObjectName("UserInfo")
        self.label = QtWidgets.QLabel(self.UserInfo)
        self.label.setGeometry(QtCore.QRect(20, 30, 56, 12))
        self.label.setObjectName("label")
        self.UserID = QtWidgets.QLineEdit(self.UserInfo)
        self.UserID.setText('Enter the ID')
        self.UserID.setEnabled(True)
        self.UserID.setGeometry(QtCore.QRect(46, 25, 113, 20))
        self.UserID.setMouseTracking(True)
        self.UserID.setFrame(False)
        self.UserID.setObjectName("UserID")
        self.label_2 = QtWidgets.QLabel(self.UserInfo)
        self.label_2.setGeometry(QtCore.QRect(210, 30, 56, 12))
        self.label_2.setObjectName("label_2")
        self.UserPW = QtWidgets.QLineEdit(self.UserInfo)
        self.UserPW.setText('Enter the Password')
        self.UserPW.setEnabled(True)
        self.UserPW.setGeometry(QtCore.QRect(240, 25, 113, 20))
        self.UserPW.setMouseTracking(True)
        self.UserPW.setFrame(False)
        self.UserPW.setObjectName("UserPW")
        self.AdminInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.AdminInfo.setGeometry(QtCore.QRect(30, 350, 451, 91))
        self.AdminInfo.setStyleSheet("color: rgb(255, 255, 255);")
        self.AdminInfo.setFlat(False)
        self.AdminInfo.setCheckable(False)
        self.AdminInfo.setObjectName("AdminInfo")
        self.alphaButton = QtWidgets.QRadioButton(self.AdminInfo)
        self.alphaButton.click()
        self.alphaButton.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.alphaButton.setObjectName("alphaButton")
        self.realButton = QtWidgets.QRadioButton(self.AdminInfo)
        self.realButton.setGeometry(QtCore.QRect(20, 60, 61, 16))
        self.realButton.setObjectName("realButton")
        self.label_alphaUrl = QtWidgets.QLabel(self.AdminInfo)
        self.label_alphaUrl.setGeometry(QtCore.QRect(90, 30, 211, 16))
        self.label_alphaUrl.setObjectName("label_alphaUrl")
        self.label_realUrl = QtWidgets.QLabel(self.AdminInfo)
        self.label_realUrl.setGeometry(QtCore.QRect(90, 60, 161, 16))
        self.label_realUrl.setObjectName("label_realUrl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.StartBtn.clicked.connect(MainWindow.executeClicked)
        self.ResetBtn.clicked.connect(MainWindow.resetClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def executeClicked(self):
        if self.alphaButton.isChecked():
            InitUserDeviceController(self,
                                     self.stateBrowser,
                                     self.UserID.text(),
                                     self.UserPW.text(),
                                     self.TestID.text(),
                                     "headless"
                                     ).start()
        pass

    def resetClicked(self):
        pass


    def closeEvent(self, event):
        self.deleteLater()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Reset.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#fdfdfd;\">기기 초기화</span></p></body></html>"))
        self.State.setText(_translate("MainWindow", "상태"))
        self.ResetInfo.setTitle(_translate("MainWindow", "초기화 계정"))
        self.label_5.setText(_translate("MainWindow", "ID :"))
        self.SERIES.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#04cf59;\">SERIES Automation</span></p></body></html>"))
        self.StartBtn.setText(_translate("MainWindow", "실행"))
        self.ResetBtn.setText(_translate("MainWindow", "초기화"))
        self.UserInfo.setTitle(_translate("MainWindow", "사용자 계정"))
        self.label.setText(_translate("MainWindow", "ID :"))
        self.label_2.setText(_translate("MainWindow", "PW :"))
        self.AdminInfo.setTitle(_translate("MainWindow", "어드민 URL"))
        self.alphaButton.setText(_translate("MainWindow", "ALPHA "))
        self.realButton.setText(_translate("MainWindow", "REAL"))
        self.label_alphaUrl.setText(_translate("MainWindow", "https://alpha-iims.navercorp.com"))
        self.label_realUrl.setText(_translate("MainWindow", "https://iims.navercorp.com"))
